language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-22.0.0
    - android-22
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-17
    - sys-img-armeabi-v7a-android-18
jdk:
  - oraclejdk8

sudo: false

before_install:
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

install:
  - ./gradlew assemble

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - ./gradlew fullTest
